name: Website Bug
description: Report a bug or issue related to website.
title: "[Website] BUG"
labels: ["bug", "site"]
body:
  - type: dropdown
    id: section
    attributes:
      label: Section
      description: The section where the bug occurs.
      multiple: true
      options:
        - Resource Packs
        - Addons
        - Crafting Tweaks
        - Home
        - Privacy Policy
        - Terms and Conditions
    validations:
      required: true
  - type: input
    id: pack_name
    attributes:
      label: Pack name
      description: If applicable, enter the name of pack or combination of packs which has the bug.
      placeholder: "Example: Trading Helper"
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "Example: The pack icon for Trading Helper uses the wrong icon."
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: Media
      description: If applicable, add screenshots or videos to help explain your problem.
    validations:
      required: false
  - type: input
    id: web_browser
    attributes:
      label: Web browser
      description: The web browser you are using to browse Bedrock Tweaks.
      placeholder: "Example: Chrome"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: If applicable, enter your operating system.
      placeholder: "Example: Android 15"
    validations:
      required: false
  - type: input
    id: minecraft_version
    attributes:
      label: Minecraft version
      description: If applicable, enter your Minecraft version.
      placeholder: "Example: 1.21.100"
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
