/**
 * Shared scaffolding for the GameTest suite.
 *
 * Graves is harder to test than a mob-behaviour pack for three reasons, and
 * this module is where each one is answered once:
 *
 *  1. **The index is world state.** Records live in world dynamic properties
 *     (`bt_gc_graves:idx:<owner>`, `:owners`), so a test that dies halfway
 *     leaves debris behind for the next one — and for the dev world the suite
 *     is running in. Everything the harness creates is tracked and undone in
 *     `test.runOnFinish`, and nothing outside that set is ever touched.
 *  2. **Config is world-global, tests are not.** A runset places its tests
 *     side by side and runs them at the same time, so two tests flipping
 *     `allowRobbing` would read each other's value. `withServerConfig` funnels
 *     every config-SENSITIVE body through one promise chain — readers included,
 *     not just writers, because a neighbour's patch is just as visible to a
 *     test that only reads. Tests that touch no config stay parallel.
 *  3. **A test needs a structure, and it has to be a real file.** The pad is
 *     generated by `tools/pad.mjs` into
 *     `packs/BP/structures/graves/pad.mcstructure`. GameTest does not resolve a
 *     structure written from script into the WORLD store; it quietly
 *     substitutes a default area instead. `pad_probe` guards against that.
 *
 * @see index.ts for how to run the suite.
 */
import { BlockPermutation, EntityComponentTypes, GameMode, ItemStack, world } from '@minecraft/server';
// `Block` must be imported explicitly: the generator filter puts a global
// `Block` (the block BEHAVIOUR document) in scope, and it wins otherwise.
import type { Block, Container, Entity, EntityEquippableComponent, Player, Vector3 } from '@minecraft/server';
import { register, registerAsync } from '@minecraft/server-gametest';
import type { RegistrationBuilder, SimulatedPlayer, Test } from '@minecraft/server-gametest';
import { config } from '../registration';
import { GRAVE_ENTITY, PROP_DISABLED, PROP_IDX_PREFIX, PROP_OWNERS, PROP_PREV_KEEP_INVENTORY } from '../constants';
import { ownerIds, visibleRecordsOf } from '../index/store';
import type { GraveRecord, Placement } from '../types';

/** Test class name — `/gametest run graves:<name>`. */
export const SUITE = 'graves';

/**
 * Implemented and expected to pass: `/gametest runset graves_ready`.
 *
 * Not `graves`: the class name is a set of its own, so `runset graves` runs
 * every test registered under it — the unwritten ones included — and the
 * distinction the tags exist to draw would be lost.
 */
export const TAG_READY = 'graves_ready';

/** Registered but not written yet: `/gametest runset graves_todo`. */
export const TAG_TODO = 'graves_todo';

/** Group tags, so one area can be run on its own. */
export const TAG_PLACEMENT = 'graves_placement';
export const TAG_CAPTURE = 'graves_capture';
export const TAG_OPEN = 'graves_open';
export const TAG_STATE = 'graves_state';

const DEFAULT_TICKS = 200;

/**
 * For any test that takes the config lock. Those bodies run one at a time, so a
 * test's tick budget has to cover every other locked test ahead of it in the
 * queue, not just its own work — and the whole class is meant to be runnable in
 * one go, so the queue is as long as the suite. maxTicks is a ceiling, not a
 * cost: a test that finishes in two seconds still finishes in two seconds.
 */
export const LOCKED_TICKS = 6000;
const DEFAULT_PADDING = 2;

// ─── The pad ───────────────────────────────────────────────────────────────────

/**
 * The test structure: a hollow 16³ box with a stone floor at y = 0, generated
 * by `tools/pad.mjs` into `packs/BP/structures/graves/pad.mcstructure`.
 *
 * It has to be a real file in the BEHAVIOUR PACK. Writing it from script with
 * `structureManager.createEmpty(..., StructureSaveMode.World)` looks like it
 * works — the game stores it and `getWorldStructureIds()` lists it — but
 * GameTest does not resolve world structures. It silently falls back to a small
 * default area instead, and the first `setBlockType` past that area throws
 * `gameTest.assert.couldNotSetBlock` with nothing to say why. `pad_probe`
 * below is the guard against that failure mode coming back.
 */
export const PAD_STRUCTURE = 'graves:pad';

export const PAD_SIZE: Vector3 = { x: 16, y: 16, z: 16 };

/** Relative y of the stone floor. Anything a test stands on starts at y = 1. */
export const PAD_FLOOR_Y = 0;

/** Relative centre of the pad, one block above the floor. */
export const PAD_CENTER: Vector3 = { x: 8, y: PAD_FLOOR_Y + 1, z: 8 };

export const PAD_FLOOR_BLOCK = 'minecraft:stone';

/**
 * Where pad cell (0,0,0) sits in GameTest's own relative frame.
 *
 * The two frames are NOT the same, which is worth stating plainly because
 * every coordinate in every test depends on it. GameTest's relative (0,0,0) is
 * the STRUCTURE BLOCK — measured in game: `(0,0,0)` reads back
 * `minecraft:structure_block` with `minecraft:redstone_block` powering it at
 * `(0,-1,0)` — and the structure itself is placed offset from that. So the pad
 * floor, which this file calls y = 0, is not at GameTest's y = 0.
 *
 * The offset is discovered rather than hard-coded: it is a framework detail
 * nothing documents, and a wrong constant would silently shift every
 * expectation by a block, which is exactly the bug that is easiest to read as
 * "the addon is broken".
 */
let padOrigin: Vector3 | undefined;

const readsAs = (test: Test, at: Vector3, typeId: string): boolean => {
  try {
    return test.getBlock(at).typeId === typeId;
  } catch {
    return false;
  }
};

/** Find pad (0,0,0) by looking for the floor's near AND far corner together. */
export function discoverPadOrigin(test: Test): Vector3 {
  if (padOrigin) {
    return padOrigin;
  }

  for (let y = 0; y <= 3; y++) {
    for (let x = 0; x <= 3; x++) {
      for (let z = 0; z <= 3; z++) {
        const near = { x, y, z };
        const far = { x: x + PAD_SIZE.x - 1, y, z: z + PAD_SIZE.z - 1 };

        // Both corners pins it: one alone would also match stray world stone.
        if (readsAs(test, near, PAD_FLOOR_BLOCK) && readsAs(test, far, PAD_FLOOR_BLOCK)) {
          padOrigin = near;
          console.info(`[graves:test] pad (0,0,0) is at gametest-relative ${String(x)} ${String(y)} ${String(z)}`);

          return near;
        }
      }
    }
  }

  throw new Error(`the pad floor is not in play — no ${String(PAD_SIZE.x)}-wide ${PAD_FLOOR_BLOCK} plane near the structure block. Run 'yarn pad', rebuild, reload the world.`);
}

/** A pad cell in GameTest's relative frame. */
export const padAt = (test: Test, at: Vector3): Vector3 => {
  const origin = discoverPadOrigin(test);

  return { x: at.x + origin.x, y: at.y + origin.y, z: at.z + origin.z };
};

/** A pad cell in world coordinates — what the solver takes and returns. */
export const padWorld = (test: Test, at: Vector3): Vector3 => test.worldBlockLocation(padAt(test, at));

/** The block in a pad cell. Note `test.getBlock` takes RELATIVE, never world, coordinates. */
export const padBlock = (test: Test, at: Vector3): Block => test.getBlock(padAt(test, at));

/** A world position back in pad coordinates. */
export const padOf = (test: Test, world: Vector3): Vector3 => {
  const origin = discoverPadOrigin(test);
  const relative = test.relativeBlockLocation(world);

  return { x: relative.x - origin.x, y: relative.y - origin.y, z: relative.z - origin.z };
};

/**
 * Prove the pad is the structure in play.
 *
 * Not by measuring the area: `test.getBlock` happily reads far outside it, so
 * walking out until something throws reports the walk limit and nothing else.
 * The pad has a shape instead — a solid floor and air above it, corner to
 * corner — and reading that shape back is what tells the two cases apart.
 */
export function padIsLoaded(test: Test): string | undefined {
  let origin: Vector3;

  try {
    origin = discoverPadOrigin(test);
  } catch (error) {
    return String(error);
  }

  const world0 = padWorld(test, { x: 0, y: 0, z: 0 });

  console.info(`[graves:test] dimension ${test.getDimension().id}, pad (0,0,0) at gametest-relative ${String(origin.x)} ${String(origin.y)} ${String(origin.z)} = world ${String(world0.x)} ${String(world0.y)} ${String(world0.z)}`);

  const last = { x: PAD_SIZE.x - 1, y: PAD_SIZE.y - 1, z: PAD_SIZE.z - 1 };
  const samples: [string, Vector3, string][] = [
    ['floor 0,0,0', { x: 0, y: 0, z: 0 }, PAD_FLOOR_BLOCK],
    ['floor 15,0,0', { x: last.x, y: 0, z: 0 }, PAD_FLOOR_BLOCK],
    ['floor 0,0,15', { x: 0, y: 0, z: last.z }, PAD_FLOOR_BLOCK],
    ['floor 15,0,15', { x: last.x, y: 0, z: last.z }, PAD_FLOOR_BLOCK],
    ['air 8,1,8', PAD_CENTER, 'minecraft:air'],
    ['air 15,15,15', last, 'minecraft:air'],
  ];

  const broken: string[] = [];

  for (const [label, at, want] of samples) {
    let seen: string;

    try {
      seen = padBlock(test, at).typeId;
    } catch (error) {
      seen = `<unreadable: ${String(error)}>`;
    }

    console.info(`[graves:test]   ${label} = ${seen}`);

    if (seen !== want) {
      broken.push(`${label} is ${seen}, wanted ${want}`);
    }
  }

  return broken.length === 0 ? undefined : `the pad is not intact: ${broken.join(', ')}`;
}

// ─── Cleanup ───────────────────────────────────────────────────────────────────

/**
 * Per-test bookkeeping.
 *
 * Keyed by the Test, NOT module-global, and that is the whole point: a runset
 * places its tests side by side and runs them AT THE SAME TIME. One shared set
 * meant the first test to finish disconnected every other test's simulated
 * players and deleted their index records out from under them — which shows up
 * as `Failed to call function 'kill' due to Entity being invalid` in a test
 * that never touched that player.
 *
 * `owners` holds only ids the harness minted, so cleanup can drop those index
 * records and nothing else: a dev world's real graves are not the suite's to
 * throw away.
 */
interface Scope {
  guests: Set<SimulatedPlayer>;
  owners: Set<string>;
}

const scopes = new Map<Test, Scope>();

const scopeOf = (test: Test): Scope => {
  const existing = scopes.get(test);

  if (existing) {
    return existing;
  }

  const fresh: Scope = { guests: new Set(), owners: new Set() };

  scopes.set(test, fresh);

  return fresh;
};

/** What a dynamic property is allowed to hold — mirrors `getDynamicProperty`. */
type PropertyValue = string | number | boolean | Vector3 | undefined;

/** World properties as they were before the suite touched anything. */
let before: { disabled: PropertyValue; prevKeepInventory: PropertyValue } | undefined;

/** Remember the addon's pre-suite world state. Called once, from `index.ts`. */
export function snapshotWorld(): void {
  before = {
    disabled: world.getDynamicProperty(PROP_DISABLED),
    prevKeepInventory: world.getDynamicProperty(PROP_PREV_KEEP_INVENTORY),
  };
}

/** Register an owner id as this test's, so its cleanup may drop those records. */
export const claimOwner = (test: Test, ownerId: string): void => {
  scopeOf(test).owners.add(ownerId);
};

/** Every grave entity standing inside this test's own volume. */
export function gravesInPad(test: Test): Entity[] {
  return test.getDimension().getEntities({ type: GRAVE_ENTITY, location: padWorld(test, { x: 0, y: 0, z: 0 }), volume: PAD_SIZE });
}

/** Loose item entities lying in this test's pad. */
export function itemsInPad(test: Test): Entity[] {
  return test.getDimension().getEntities({ type: 'minecraft:item', location: padWorld(test, { x: 0, y: 0, z: 0 }), volume: PAD_SIZE });
}

/**
 * Undo everything one test did: its own index records, every grave entity
 * inside the pad, and the two world switches the admin paths write. Runs even
 * when the test fails, which is the case that matters.
 */
export function cleanup(test: Test): void {
  const scope = scopeOf(test);

  scopes.delete(test);

  for (const guest of scope.guests) {
    try {
      guest.disconnect();
    } catch {
      // Already torn down by the framework — nothing left to say goodbye to.
    }
  }

  for (const ownerId of scope.owners) {
    world.setDynamicProperty(`${PROP_IDX_PREFIX}${ownerId}`, undefined);
  }

  world.setDynamicProperty(PROP_OWNERS, JSON.stringify(ownerIds().filter(id => !scope.owners.has(id))));

  for (const grave of gravesInPad(test)) {
    grave.remove();
  }

  if (before) {
    world.setDynamicProperty(PROP_DISABLED, before.disabled);
    world.setDynamicProperty(PROP_PREV_KEEP_INVENTORY, before.prevKeepInventory);
  }

  world.gameRules.keepInventory = true;
}

// ─── Terrain ───────────────────────────────────────────────────────────────────

const inPad = (at: Vector3): boolean =>
  at.x >= 0 && at.x < PAD_SIZE.x && at.y >= 0 && at.y < PAD_SIZE.y && at.z >= 0 && at.z < PAD_SIZE.z;

/**
 * Fill an inclusive pad-relative box. Corners may be given in any order.
 *
 * Writes through the DIMENSION, not `test.setBlockType`: the GameTest helper
 * refuses fluids and reports it as a bare `gameTest.assert.couldNotSetBlock`
 * with no block name and no coordinate, which is a miserable thing to debug.
 * The bounds check the helper was giving us is done here instead, and says
 * which cell was out of range.
 */
export function fill(test: Test, from: Vector3, to: Vector3, blockType: string): void {
  fillPermutation(test, from, to, BlockPermutation.resolve(blockType));
}

/** `fill`, for a block whose STATES matter — flowing fluid, stair facing, half slabs. */
export function fillPermutation(test: Test, from: Vector3, to: Vector3, permutation: BlockPermutation): void {
  for (let x = Math.min(from.x, to.x); x <= Math.max(from.x, to.x); x++) {
    for (let y = Math.min(from.y, to.y); y <= Math.max(from.y, to.y); y++) {
      for (let z = Math.min(from.z, to.z); z <= Math.max(from.z, to.z); z++) {
        const at = { x, y, z };

        if (!inPad(at)) {
          throw new Error(`fill: pad ${String(x)} ${String(y)} ${String(z)} is outside the ${String(PAD_SIZE.x)}³ pad`);
        }

        // `test.setBlockType` refuses fluids outright (a bare
        // `gameTest.assert.couldNotSetBlock`, no block name, no coordinate).
        // The permutation path is a different code path and does take them;
        // going through the dimension is the last resort, because it is also
        // the one that throws when the area is not ticking yet.
        try {
          test.setBlockPermutation(permutation, padAt(test, at));
        } catch {
          test.getDimension().setBlockPermutation(padWorld(test, at), permutation);
        }
      }
    }
  }
}

/** One block, same rules as `fill`. */
export function place(test: Test, at: Vector3, blockType: string): void {
  fill(test, at, at, blockType);
}

/**
 * Assert a solved placement landed on a pad-relative cell.
 *
 * The solver works in absolute coordinates, so both sides are compared there;
 * the failure message translates back to pad coordinates, which is the only
 * frame a reader of the test can check by eye.
 */
export function expectPlacementAt(test: Test, placement: Placement, at: Vector3, note: string): void {
  const expected = padWorld(test, at);
  const got = padOf(test, { x: placement.x, y: placement.y, z: placement.z });
  const matches = placement.x === expected.x && placement.y === expected.y && placement.z === expected.z;

  test.assert(
    matches,
    `${note}: expected pad ${String(at.x)} ${String(at.y)} ${String(at.z)}, got ${String(got.x)} ${String(got.y)} ${String(got.z)}`,
  );
}

// ─── Registration ──────────────────────────────────────────────────────────────

export interface TestOptions {
  /** Ticks before the test times out. Default 200 (10 s). */
  ticks?: number;
  /** Blocks of empty space reserved around the pad. Default 8. */
  padding?: number;
  /** Group tags, on top of the ready/todo tag. */
  tags?: readonly string[];
}

const apply = (builder: RegistrationBuilder, tag: string, options: TestOptions): RegistrationBuilder => {
  builder
    .structureName(PAD_STRUCTURE)
    .maxTicks(options.ticks ?? DEFAULT_TICKS)
    .padding(options.padding ?? DEFAULT_PADDING)
    .tag(tag);

  for (const extra of options.tags ?? []) {
    builder.tag(extra);
  }

  return builder;
};

/**
 * Put a result in the content log.
 *
 * GameTest reports failures on screen and writes nothing to the log, so the
 * one artefact that survives a run says nothing about what actually broke.
 * Every test therefore reports itself. A thrown assertion is also turned into
 * an explicit `test.fail` rather than being left to propagate: an async body
 * that rejects surfaces as a bare `Unhandled promise rejection` with the test
 * name nowhere in it.
 *
 * PASS here means the body ran to completion without an assertion throwing.
 * Tests in this suite call `test.succeed()` themselves, so that is the same
 * thing; a body built on `succeedWhen` would need a different signal.
 */
const report = (test: Test, name: string, error?: unknown): void => {
  if (error === undefined) {
    console.info(`[graves:test] PASS ${name}`);

    return;
  }

  const message = error instanceof Error ? error.message : String(error);

  console.error(`[graves:test] FAIL ${name} — ${message}`);

  try {
    test.fail(message);
  } catch {
    // Already finished; the log line is the record that matters.
  }
};

/** Cleanup can throw too, and a throw inside `runOnFinish` is silent. */
const sweep = (test: Test, name: string): void => {
  try {
    cleanup(test);
  } catch (error) {
    console.error(`[graves:test] cleanup failed after ${name}: ${String(error)}`);
  }
};

/** A synchronous test, cleaned up on the way out. */
export function graveTest(name: string, body: (test: Test) => void, options: TestOptions = {}): RegistrationBuilder {
  return apply(register(SUITE, name, (test) => {
    test.runOnFinish(() => {
      sweep(test, name);
    });

    try {
      body(test);
      report(test, name);
    } catch (error) {
      report(test, name, error);
    }
  }), TAG_READY, options);
}

/** An async test — anything that waits on ticks, deaths or the container watch. */
export function graveTestAsync(name: string, body: (test: Test) => Promise<void>, options: TestOptions = {}): RegistrationBuilder {
  return apply(registerAsync(SUITE, name, async (test) => {
    test.runOnFinish(() => {
      sweep(test, name);
    });

    try {
      await body(test);
      report(test, name);
    } catch (error) {
      report(test, name, error);
    }
  }), TAG_READY, options);
}

/**
 * A test that is planned but not written. It registers under `graves_todo`
 * only, so `/gametest runset graves` stays a signal rather than a wall of red,
 * and it fails loudly when run so the remaining work stays visible.
 *
 * Filling one in is a one-line change: `todo(...)` becomes `graveTest(...)`.
 */
export function todo(name: string, plan: string, options: TestOptions = {}): RegistrationBuilder {
  return apply(register(SUITE, name, (test) => {
    // The plan goes to the content log, not to chat: `test.print` broadcasts to
    // every player in the world, and a runset would bury the game under it.
    console.warn(`[graves:test] ${name} is not implemented — ${plan}`);
    test.fail(`not implemented: ${name}`);
  }), TAG_TODO, { ticks: 20, ...options });
}

// ─── Config ────────────────────────────────────────────────────────────────────

type ServerConfig = ReturnType<typeof config.server.get>;
type ServerConfigPatch = Parameters<typeof config.server.patch>[0];

/** One promise chain, so only one config-mutating body runs at a time. */
let chain: Promise<unknown> = Promise.resolve();

/** Queue `body` behind every other serialized body. A rejection never poisons the chain. */
export function serial<T>(body: () => Promise<T>): Promise<T> {
  const run = chain.then(body);

  chain = run.catch(() => undefined);

  return run;
}

/**
 * Run `body` with the server config patched, then put the whole scope back
 * exactly as it was — `set` on the root reverts keys the snapshot omits too,
 * so nothing a test writes can survive it.
 */
export function withServerConfig<T>(test: Test, overrides: ServerConfigPatch, body: () => Promise<T>): Promise<T> {
  return serial(async () => {
    // The queue can be long enough that this test ran out of ticks while
    // waiting. Saying so beats the bare `GameTestCompletedError ... can no
    // longer access method: getDimension` that the first `test.` call raises.
    if (test.isCompleted()) {
      throw new Error('timed out waiting for the config lock — raise maxTicks on this test, or run one group at a time');
    }

    const snapshot: ServerConfig = config.server.get();

    config.server.patch(overrides);

    try {
      return await body();
    } finally {
      config.server.set(snapshot);
    }
  });
}

// ─── Players ───────────────────────────────────────────────────────────────────

/**
 * The player who started the run.
 *
 * Prefer this over `arrive` wherever a test needs a Player but not a BODY —
 * the placement solver, for one, only wants an owner to read a spawn point
 * off. A simulated player that is spawned and torn down inside one short test
 * makes the framework log `InvalidEntityError ... at loadPlayerValues`: it
 * subscribes to `playerSpawn` and reads the new player's dynamic properties,
 * and that queued handler runs after the test has already removed them. It is
 * noise from a real handle going stale, not a fault in this addon, and the way
 * to not produce it is to not churn players.
 */
export function anyPlayer(): Player {
  const [player] = world.getAllPlayers();

  if (!player) {
    throw new Error('this test needs a player in the world — run it from in game, not from a script');
  }

  return player;
}

/**
 * A simulated player inside the pad, registered as ours so its graves are
 * cleaned up afterwards. `at` is relative to the pad.
 *
 * Only for tests that need a body to die, hold an item or swing at something.
 * See `anyPlayer` for why a short-lived one is worth avoiding.
 */
export function arrive(test: Test, name: string, at: Vector3 = PAD_CENTER, gameMode: GameMode = GameMode.Survival): SimulatedPlayer {
  const player = test.spawnSimulatedPlayer(padAt(test, at), name, gameMode);

  const scope = scopeOf(test);

  scope.owners.add(player.id);
  scope.guests.add(player);

  return player;
}

/**
 * Kill `player` and resolve once the capture handler has run — the index
 * record is the proof, so there is no tick count to guess at.
 *
 * UNVERIFIED: a simulated player respawns wherever the world says, not inside
 * the pad, so a test that goes on to use it must teleport it back first.
 */
export async function dieMaybe(test: Test, player: SimulatedPlayer, waitTicks = 40): Promise<GraveRecord | undefined> {
  const ownerId = player.id;
  const already = new Set(visibleRecordsOf(ownerId).map(record => record.id));

  player.kill();
  await test.idle(waitTicks);

  return visibleRecordsOf(ownerId).find(record => !already.has(record.id));
}

/**
 * Kill `player` and return the grave it left, failing if it left none.
 *
 * Identified by being NEW rather than by being first: a test that dies twice
 * would otherwise keep asserting against the first death's grave.
 */
export async function die(test: Test, player: SimulatedPlayer): Promise<GraveRecord> {
  const record = await dieMaybe(test, player);

  if (!record) {
    // `player.name` throws on a dead handle, which would replace this message
    // with a bare "Failed to get property 'name'" and hide what actually failed.
    const who = player.isValid ? player.name : 'a player that is no longer valid';

    throw new Error(`no grave was indexed for ${who}`);
  }

  return record;
}

/** Back on their feet inside the pad. A respawn puts a player at world spawn, not here. */
export async function revive(test: Test, player: SimulatedPlayer, at: Vector3 = PAD_CENTER): Promise<void> {
  player.respawn();
  await test.idle(5);
  player.teleport(padWorld(test, at), { dimension: test.getDimension() });
  await test.idle(2);
}

export const inventoryOf = (player: Player): Container => {
  const container = player.getComponent<EntityComponentTypes.Inventory>(EntityComponentTypes.Inventory)?.container;

  if (!container) {
    throw new Error(`${player.name} has no inventory container`);
  }

  return container;
};

export const equipmentOf = (player: Player): EntityEquippableComponent => {
  const equippable = player.getComponent<EntityComponentTypes.Equippable>(EntityComponentTypes.Equippable);

  if (!equippable) {
    throw new Error(`${player.name} has no equippable component`);
  }

  return equippable;
};

/**
 * Narrow away an `undefined` with a message.
 *
 * `test.assert` reports the problem but does not narrow the type, so a plain
 * assert leaves every later read on the value needing a `?.` that hides which
 * line actually failed. Throwing is also what GameTest wants: the harness turns
 * a throw into a named `FAIL` line in the content log.
 */
export function must<T>(value: T | undefined, message: string): T {
  if (value === undefined) {
    throw new Error(message);
  }

  return value;
}

/** Put a known stack in a known slot, so the assertion can name both. */
export const giveItem = (player: Player, slot: number, typeId: string, amount = 1): ItemStack => {
  const stack = new ItemStack(typeId, amount);

  inventoryOf(player).setItem(slot, stack);

  return stack;
};

/** `a.typeId === b.typeId && a.amount === b.amount`, with a readable failure. */
export const expectStack = (test: Test, actual: ItemStack | undefined, want: ItemStack | undefined, note: string): void => {
  const show = (stack?: ItemStack): string => (stack ? `${stack.typeId} x${String(stack.amount)}` : 'nothing');

  test.assert(
    actual?.typeId === want?.typeId && actual?.amount === want?.amount,
    `${note}: expected ${show(want)}, found ${show(actual)}`,
  );
};

/**
 * The grave entity a record points at. Throws rather than returning undefined:
 * GameTest turns a thrown error into a failed test with the message intact,
 * and callers get a narrowed `Entity` without a cast.
 */
export function graveOf(record: GraveRecord): Entity {
  const grave = world.getEntity(record.id);

  if (!grave) {
    throw new Error(`grave entity ${record.id} is not loaded`);
  }

  return grave;
}
