name: Add contributors to README

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!devel'

jobs:
  contributions:
    name: Add contributions to README
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        env:
          GITHUB_TOKEN: ${{ secrets.BT_CONTRIBUTORS_README_TOKEN }}
          use_username: true
          auto_detect_branch_protection: false
