name: Add contributors

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add contributors
        uses: BobAnkh/add-contributors@master
        with:
          CONTRIBUTOR: '### Thanks to all the Contributors!'
          COLUMN_PER_ROW: '6'
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMG_WIDTH: '100'
          FONT_SIZE: '14'
          PATH: 'main:/README.md'
          COMMIT_MESSAGE: 'chore(files): update contributors'
          AVATAR_SHAPE: 'round'
