give @s bt:mb.acacia_log
give @s bt:mb.acacia_planks
give @s bt:mb.amethyst_block
give @s bt:mb.ancient_debris
give @s bt:mb.andesite
give @s bt:mb.azalea_leaves
give @s bt:mb.barrel
give @s bt:mb.basalt
give @s bt:mb.bee_nest
give @s bt:mb.beehive
give @s bt:mb.birch_log
give @s bt:mb.birch_planks
give @s bt:mb.black_concrete
give @s bt:mb.blackstone
give @s bt:mb.blast_furnace
give @s bt:mb.blue_concrete
give @s bt:mb.bone_block
give @s bt:mb.brain_coral_block
give @s bt:mb.bricks
give @s bt:mb.brown_concrete
give @s bt:mb.bubble_coral_block
give @s bt:mb.calcite
give @s bt:mb.cartography_table
give @s bt:mb.chest
give @s bt:mb.chiseled_nether_bricks
give @s bt:mb.chiseled_polished_blackstone
give @s bt:mb.chiseled_stone_bricks
give @s bt:mb.clay
give @s bt:mb.coal_block
give @s bt:mb.coal_ore
give @s bt:mb.cobbled_deepslate
give @s bt:mb.cobblestone
give @s bt:mb.copper_ore
give @s bt:mb.crafting_table
give @s bt:mb.crimson_nylium
give @s bt:mb.crimson_planks
give @s bt:mb.crimson_stem
give @s bt:mb.crying_obsidian
give @s bt:mb.cut_copper
give @s bt:mb.cyan_concrete
give @s bt:mb.dark_oak_log
give @s bt:mb.dark_oak_planks
give @s bt:mb.dark_prismarine
give @s bt:mb.deepslate
give @s bt:mb.deepslate_coal_ore
give @s bt:mb.deepslate_copper_ore
give @s bt:mb.deepslate_diamond_ore
give @s bt:mb.deepslate_emerald_ore
give @s bt:mb.deepslate_gold_ore
give @s bt:mb.deepslate_iron_ore
give @s bt:mb.deepslate_lapis_lazuli_ore
give @s bt:mb.deepslate_redstone_ore
give @s bt:mb.diamond_block
give @s bt:mb.diamond_ore
give @s bt:mb.diorite
give @s bt:mb.dirt
give @s bt:mb.dispenser
give @s bt:mb.dried_kelp_block
give @s bt:mb.dripstone
give @s bt:mb.dropper
give @s bt:mb.emerald_block
give @s bt:mb.emerald_ore
give @s bt:mb.enchanting_table
give @s bt:mb.end_stone
give @s bt:mb.end_stone_bricks
give @s bt:mb.ender_chest
give @s bt:mb.exposed_cut_copper
give @s bt:mb.fire_coral_block
give @s bt:mb.fletching_table
give @s bt:mb.flowering_azalea_leaves
give @s bt:mb.furnace
give @s bt:mb.gilded_blackstone
give @s bt:mb.glowstone
give @s bt:mb.gold_block
give @s bt:mb.gold_ore
give @s bt:mb.granite
give @s bt:mb.grass_block
give @s bt:mb.gravel
give @s bt:mb.gray_concrete
give @s bt:mb.green_concrete
give @s bt:mb.hay_block
give @s bt:mb.honey_block
give @s bt:mb.honeycomb_block
give @s bt:mb.horn_coral_block
give @s bt:mb.iron_block
give @s bt:mb.iron_ore
give @s bt:mb.jukebox
give @s bt:mb.jungle_log
give @s bt:mb.jungle_planks
give @s bt:mb.lapis_block
give @s bt:mb.lapis_ore
give @s bt:mb.light_blue_concrete
give @s bt:mb.light_gray_concrete
give @s bt:mb.lime_concrete
give @s bt:mb.lodestone
give @s bt:mb.loom
give @s bt:mb.magenta_concrete
give @s bt:mb.magma_block
give @s bt:mb.mangrove_log
give @s bt:mb.mangrove_planks
give @s bt:mb.melon
give @s bt:mb.moss_block
give @s bt:mb.mossy_cobblestone
give @s bt:mb.mud
give @s bt:mb.mud_bricks
give @s bt:mb.mycelium
give @s bt:mb.nether_bricks
give @s bt:mb.nether_gold_ore
give @s bt:mb.nether_quartz_ore
give @s bt:mb.nether_wart_block
give @s bt:mb.netherite_block
give @s bt:mb.netherrack
give @s bt:mb.noteblock
give @s bt:mb.oak_log
give @s bt:mb.oak_planks
give @s bt:mb.observer
give @s bt:mb.obsidian
give @s bt:mb.ochre_froglight
give @s bt:mb.orange_concrete
give @s bt:mb.oxidized_cut_copper
give @s bt:mb.packed_ice
give @s bt:mb.packed_mud
give @s bt:mb.pearlescent_froglight
give @s bt:mb.pink_concrete
give @s bt:mb.piston
give @s bt:mb.podzol
give @s bt:mb.polished_andesite
give @s bt:mb.polished_basalt
give @s bt:mb.polished_blackstone
give @s bt:mb.polished_blackstone_bricks
give @s bt:mb.polished_deepslate
give @s bt:mb.polished_diorite
give @s bt:mb.polished_granite
give @s bt:mb.prismarine
give @s bt:mb.prismarine_bricks
give @s bt:mb.pumpkin
give @s bt:mb.purple_concrete
give @s bt:mb.purpur_block
give @s bt:mb.quartz_block
give @s bt:mb.raw_copper_block
give @s bt:mb.raw_gold_block
give @s bt:mb.raw_iron_block
give @s bt:mb.red_concrete
give @s bt:mb.red_mushroom_block
give @s bt:mb.red_nether_bricks
give @s bt:mb.red_sand
give @s bt:mb.red_sandstone
give @s bt:mb.redstone_block
give @s bt:mb.redstone_lamp_lit
give @s bt:mb.redstone_lamp_unlit
give @s bt:mb.redstone_ore
give @s bt:mb.respawn_anchor
give @s bt:mb.sand
give @s bt:mb.sandstone
give @s bt:mb.sea_lantern
give @s bt:mb.shroomlight
give @s bt:mb.shulker_box
give @s bt:mb.sculk
give @s bt:mb.slime_block
give @s bt:mb.smithing_table
give @s bt:mb.smoker
give @s bt:mb.smooth_stone
give @s bt:mb.snow_block
give @s bt:mb.soul_sand
give @s bt:mb.sponge
give @s bt:mb.spruce_log
give @s bt:mb.spruce_planks
give @s bt:mb.sticky_piston
give @s bt:mb.stone
give @s bt:mb.stone_bricks
give @s bt:mb.target
give @s bt:mb.terracotta
give @s bt:mb.tnt
give @s bt:mb.tube_coral_block
give @s bt:mb.tuff
give @s bt:mb.verdant_froglight
give @s bt:mb.warped_nylium
give @s bt:mb.warped_planks
give @s bt:mb.warped_stem
give @s bt:mb.warped_wart_block
give @s bt:mb.weathered_cut_copper
give @s bt:mb.white_concrete
give @s bt:mb.white_wool
give @s bt:mb.yellow_concrete
