give @s bt:hh.bdoubleo100
give @s bt:hh.biffa2001
give @s bt:hh.cubfan135
give @s bt:hh.docm77
give @s bt:hh.etho
give @s bt:hh.falsesymmetry
give @s bt:hh.goodtimeswithscar
give @s bt:hh.grian
give @s bt:hh.hypnotizd
give @s bt:hh.ijevin
give @s bt:hh.impulsesv
give @s bt:hh.iskall85
give @s bt:hh.jessassin
give @s bt:hh.joehillssays
give @s bt:hh.keralis1
give @s bt:hh.mumbo_jumbo
give @s bt:hh.pythongb
give @s bt:hh.renthedog
give @s bt:hh.stressmonster101
give @s bt:hh.tango_tek
give @s bt:hh.tinfoilchef
give @s bt:hh.vintagebeef
give @s bt:hh.welsknight
give @s bt:hh.xbcrafted
give @s bt:hh.xisuma
give @s bt:hh.zedaph
give @s bt:hh.zombiecleo