give @s bt:mb.nether_quartz_ore
give @s bt:mb.nether_wart_block
give @s bt:mb.netherite_block
give @s bt:mb.netherrack
give @s bt:mb.noteblock
give @s bt:mb.oak_log
give @s bt:mb.oak_planks
give @s bt:mb.observer
give @s bt:mb.obsidian
give @s bt:mb.ochre_froglight
give @s bt:mb.orange_concrete
give @s bt:mb.oxidized_cut_copper
give @s bt:mb.packed_ice
give @s bt:mb.packed_mud
give @s bt:mb.pearlescent_froglight
give @s bt:mb.pink_concrete
give @s bt:mb.piston
give @s bt:mb.podzol
give @s bt:mb.polished_andesite
give @s bt:mb.polished_basalt
give @s bt:mb.polished_blackstone
give @s bt:mb.polished_blackstone_bricks
give @s bt:mb.polished_deepslate
give @s bt:mb.polished_diorite
give @s bt:mb.polished_granite
give @s bt:mb.prismarine
give @s bt:mb.prismarine_bricks
