give @s bt:mb.pumpkin
give @s bt:mb.purple_concrete
give @s bt:mb.purpur_block
give @s bt:mb.quartz_block
give @s bt:mb.raw_copper_block
give @s bt:mb.raw_gold_block
give @s bt:mb.raw_iron_block
give @s bt:mb.red_concrete
give @s bt:mb.red_mushroom_block
give @s bt:mb.red_nether_bricks
give @s bt:mb.red_sand
give @s bt:mb.red_sandstone
give @s bt:mb.redstone_block
give @s bt:mb.redstone_lamp_lit
give @s bt:mb.redstone_lamp_unlit
give @s bt:mb.redstone_ore
give @s bt:mb.respawn_anchor
give @s bt:mb.sand
give @s bt:mb.sandstone
give @s bt:mb.sea_lantern
give @s bt:mb.shroomlight
give @s bt:mb.shulker_box
give @s bt:mb.sculk
give @s bt:mb.slime_block
give @s bt:mb.smithing_table
give @s bt:mb.smoker
give @s bt:mb.smooth_stone
