give @s bt:mb.diorite
give @s bt:mb.dirt
give @s bt:mb.dispenser
give @s bt:mb.dried_kelp_block
give @s bt:mb.dripstone
give @s bt:mb.dropper
give @s bt:mb.emerald_block
give @s bt:mb.emerald_ore
give @s bt:mb.enchanting_table
give @s bt:mb.end_stone
give @s bt:mb.end_stone_bricks
give @s bt:mb.ender_chest
give @s bt:mb.exposed_cut_copper
give @s bt:mb.fire_coral_block
give @s bt:mb.fletching_table
give @s bt:mb.flowering_azalea_leaves
give @s bt:mb.furnace
give @s bt:mb.gilded_blackstone
give @s bt:mb.glowstone
give @s bt:mb.gold_block
give @s bt:mb.gold_ore
give @s bt:mb.granite
give @s bt:mb.grass_block
give @s bt:mb.gravel
give @s bt:mb.gray_concrete
give @s bt:mb.green_concrete
give @s bt:mb.hay_block
