give @s bt:mb.honey_block
give @s bt:mb.honeycomb_block
give @s bt:mb.horn_coral_block
give @s bt:mb.iron_block
give @s bt:mb.iron_ore
give @s bt:mb.jukebox
give @s bt:mb.jungle_log
give @s bt:mb.jungle_planks
give @s bt:mb.lapis_block
give @s bt:mb.lapis_ore
give @s bt:mb.light_blue_concrete
give @s bt:mb.light_gray_concrete
give @s bt:mb.lime_concrete
give @s bt:mb.lodestone
give @s bt:mb.loom
give @s bt:mb.magenta_concrete
give @s bt:mb.magma_block
give @s bt:mb.mangrove_log
give @s bt:mb.mangrove_planks
give @s bt:mb.melon
give @s bt:mb.moss_block
give @s bt:mb.mossy_cobblestone
give @s bt:mb.mud
give @s bt:mb.mud_bricks
give @s bt:mb.mycelium
give @s bt:mb.nether_bricks
give @s bt:mb.nether_gold_ore
