give @s bt:mb.acacia_log
give @s bt:mb.acacia_planks
give @s bt:mb.amethyst_block
give @s bt:mb.ancient_debris
give @s bt:mb.andesite
give @s bt:mb.azalea_leaves
give @s bt:mb.barrel
give @s bt:mb.basalt
give @s bt:mb.bee_nest
give @s bt:mb.beehive
give @s bt:mb.birch_log
give @s bt:mb.birch_planks
give @s bt:mb.black_concrete
give @s bt:mb.blackstone
give @s bt:mb.blast_furnace
give @s bt:mb.blue_concrete
give @s bt:mb.bone_block
give @s bt:mb.brain_coral_block
give @s bt:mb.bricks
give @s bt:mb.brown_concrete
give @s bt:mb.bubble_coral_block
give @s bt:mb.calcite
give @s bt:mb.cartography_table
give @s bt:mb.chest
give @s bt:mb.chiseled_nether_bricks
give @s bt:mb.chiseled_polished_blackstone
give @s bt:mb.chiseled_stone_bricks
