give @s bt:mb.clay
give @s bt:mb.coal_block
give @s bt:mb.coal_ore
give @s bt:mb.cobbled_deepslate
give @s bt:mb.cobblestone
give @s bt:mb.copper_ore
give @s bt:mb.crafting_table
give @s bt:mb.crimson_nylium
give @s bt:mb.crimson_planks
give @s bt:mb.crimson_stem
give @s bt:mb.crying_obsidian
give @s bt:mb.cut_copper
give @s bt:mb.cyan_concrete
give @s bt:mb.dark_oak_log
give @s bt:mb.dark_oak_planks
give @s bt:mb.dark_prismarine
give @s bt:mb.deepslate
give @s bt:mb.deepslate_coal_ore
give @s bt:mb.deepslate_copper_ore
give @s bt:mb.deepslate_diamond_ore
give @s bt:mb.deepslate_emerald_ore
give @s bt:mb.deepslate_gold_ore
give @s bt:mb.deepslate_iron_ore
give @s bt:mb.deepslate_lapis_lazuli_ore
give @s bt:mb.deepslate_redstone_ore
give @s bt:mb.diamond_block
give @s bt:mb.diamond_ore
